### ISSUE TITLE
The action can't access a repository local config

### ISSUE THREAD

**Issue by phinner** [dlavrenuek/conventional-changelog-action#115]
When specifying `config-file`, the action doesn't seem to be able to read the file, even with the full path.

![image](https://user-images.githubusercontent.com/62483793/169721685-d490c820-5dc8-4ffb-bcac-4d128868feb5.png)

**Comment by dlavrenuek** [comment]
@Phinner Thank you for reporting the issue. It has been fixed in the release [`v1.2.1`](https://github.com/dlavrenuek/conventional-changelog-action/releases/tag/v1.2.1)

**Comment by phinner** [comment]
No problem.
